### ISSUE TITLE
eyaml compatible library

### ISSUE THREAD

**Issue by mariusor** [muderjul/eyaml-ansible#1]
https://github.com/muderjul/eyaml-ansible/blob/f09923a8f0b5af886e278815d0c93cd80c54b29f/hiera-ansible.py#L39

Can you take a look if you can use something from this project for reading eyaml values? 

https://pypi.org/project/yamlpath/

**Comment by mariusor** [comment]
And maybe something like this for vault write: 

https://gist.github.com/damncabbage/12af8915e12fbf71b897

**Comment by muderjul** [comment]
Yamlpath uses the eyaml binary internally and the gist uses ansible vault (as a python module) internally. So using yamlpath would just add another dependency and in my opinion piping the data is more elegant in this case than running it through another python object.
